services:
  backend:
    build: ./docker/backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
      - ./data:/data
    env_file:
      - .env
  frontend:
    build: ./docker/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
    env_file:
      - .env